######################################################################
# Automatically generated by qmake (2.01a) Fri Mar 30 09:22:29 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += conv.h menu.h
FORMS += menu.ui
SOURCES += conv.cpp menu.cpp tif2fits2012.cpp
